# Generated by Django 3.0.6 on 2020-05-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appuser',
            table='user',
        ),
        migrations.AlterModelTable(
            name='book',
            table='book_details',
        ),
    ]
