# Generated by Django 3.0.6 on 2020-05-19 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0004_auto_20200519_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='name',
        ),
    ]
