# Generated by Django 3.0.6 on 2020-05-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0005_remove_appuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.CharField(default=1, editable=False, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
